CREATE TABLE IF NOT EXISTS fb_ai_agent_config (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    agent_name VARCHAR(128) NOT NULL COMMENT 'Agent名称',
    knowledge_ids VARCHAR(512) NULL COMMENT '知识库ID列表',
    seed_keywords TEXT NULL COMMENT '关键词种子JSON',
    target_countries TEXT NULL COMMENT '目标国家JSON',
    target_languages TEXT NULL COMMENT '目标语言JSON',
    account_ids TEXT NULL COMMENT '账号ID列表',
    monitor_group_ids TEXT NULL COMMENT '监控群组ID列表',
    lead_score_workflow_id BIGINT NULL COMMENT '线索评分工作流ID',
    comment_workflow_id BIGINT NULL COMMENT '评论生成工作流ID',
    dm_workflow_id BIGINT NULL COMMENT '私信生成工作流ID',
    auto_comment_enabled BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否自动评论',
    auto_dm_enabled BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否自动私信',
    daily_comment_limit INT NOT NULL DEFAULT 50 COMMENT '每日评论上限',
    daily_dm_limit INT NOT NULL DEFAULT 30 COMMENT '每日私信上限',
    reply_delay_range VARCHAR(128) NULL COMMENT '回复延迟范围JSON',
    persona_config TEXT NULL COMMENT '人设配置JSON',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0停用 1启用',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    KEY idx_fb_ai_agent_config_tenant (tenant_id, deleted)
) COMMENT='Facebook AI获客Agent配置';

CREATE TABLE IF NOT EXISTS fb_ai_touch_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    agent_config_id BIGINT NULL COMMENT 'Agent配置ID',
    lead_type VARCHAR(32) NULL COMMENT '线索类型',
    lead_id BIGINT NULL COMMENT '线索ID',
    target_user_id VARCHAR(128) NULL COMMENT '目标用户ID',
    target_url VARCHAR(1024) NULL COMMENT '目标链接',
    account_db_id BIGINT NULL COMMENT '执行账号数据库ID',
    account_id VARCHAR(128) NULL COMMENT 'Facebook账号ID',
    fb_account VARCHAR(255) NULL COMMENT 'Facebook账号',
    touch_type VARCHAR(32) NULL COMMENT '触达类型',
    generated_content TEXT NULL COMMENT 'AI生成内容',
    ai_reason TEXT NULL COMMENT 'AI判断理由',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0待发送 1发送中 2成功 3失败 4跳过',
    fail_reason VARCHAR(1024) NULL COMMENT '失败原因',
    scheduled_time DATETIME NULL COMMENT '计划发送时间',
    sent_time DATETIME NULL COMMENT '实际发送时间',
    operation_task_id BIGINT NULL COMMENT '关联运营任务ID',
    operation_detail_id BIGINT NULL COMMENT '关联运营任务明细ID',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    KEY idx_fb_ai_touch_record_agent (tenant_id, agent_config_id, deleted),
    KEY idx_fb_ai_touch_record_lead (tenant_id, lead_type, lead_id, deleted),
    KEY idx_fb_ai_touch_record_status (tenant_id, status, scheduled_time, deleted)
) COMMENT='Facebook AI触达记录';

ALTER TABLE fb_collect_user
    ADD COLUMN ai_tags VARCHAR(512) NULL COMMENT 'AI标签',
    ADD COLUMN intent_level VARCHAR(32) NULL COMMENT '意向等级',
    ADD COLUMN intent_reason TEXT NULL COMMENT '意向判断理由',
    ADD COLUMN sentiment VARCHAR(32) NULL COMMENT '情绪',
    ADD COLUMN lead_type VARCHAR(64) NULL COMMENT '线索类型',
    ADD COLUMN country VARCHAR(128) NULL COMMENT '国家',
    ADD COLUMN product_relevance_score INT NULL COMMENT '产品相关度',
    ADD COLUMN ai_summary TEXT NULL COMMENT 'AI摘要',
    ADD COLUMN last_ai_analyze_time DATETIME NULL COMMENT '最近AI分析时间',
    ADD COLUMN touch_status VARCHAR(32) NULL COMMENT '触达状态',
    ADD COLUMN last_touch_time DATETIME NULL COMMENT '最近触达时间';

ALTER TABLE fb_collect_post
    ADD COLUMN ai_tags VARCHAR(512) NULL COMMENT 'AI标签',
    ADD COLUMN intent_level VARCHAR(32) NULL COMMENT '意向等级',
    ADD COLUMN intent_reason TEXT NULL COMMENT '意向判断理由',
    ADD COLUMN sentiment VARCHAR(32) NULL COMMENT '情绪',
    ADD COLUMN lead_type VARCHAR(64) NULL COMMENT '线索类型',
    ADD COLUMN country VARCHAR(128) NULL COMMENT '国家',
    ADD COLUMN language VARCHAR(64) NULL COMMENT '语言',
    ADD COLUMN product_relevance_score INT NULL COMMENT '产品相关度',
    ADD COLUMN ai_summary TEXT NULL COMMENT 'AI摘要',
    ADD COLUMN last_ai_analyze_time DATETIME NULL COMMENT '最近AI分析时间',
    ADD COLUMN touch_status VARCHAR(32) NULL COMMENT '触达状态',
    ADD COLUMN last_touch_time DATETIME NULL COMMENT '最近触达时间';
