CREATE TABLE IF NOT EXISTS facebook_message_monitor_account (
    id BIGINT NOT NULL AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    mode VARCHAR(16) NOT NULL DEFAULT 'disabled',
    check_interval_minutes INT NOT NULL DEFAULT 30,
    next_check_time DATETIME NULL,
    last_check_time DATETIME NULL,
    last_success_time DATETIME NULL,
    status TINYINT NOT NULL DEFAULT 0,
    error_message VARCHAR(1024) NULL,
    creator VARCHAR(64) NULL DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) NULL DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT(1) NOT NULL DEFAULT b'0',
    tenant_id BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fb_message_monitor_account (tenant_id, account_id, deleted)
) COMMENT='Facebook消息监控账号';

CREATE TABLE IF NOT EXISTS facebook_message_conversation (
    id BIGINT NOT NULL AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    conversation_key VARCHAR(255) NOT NULL,
    target_user_id VARCHAR(128) NULL,
    target_name VARCHAR(255) NULL,
    target_url VARCHAR(1024) NULL,
    target_avatar VARCHAR(1024) NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'messenger',
    detected_language VARCHAR(64) NULL,
    reply_target_language VARCHAR(64) NULL,
    unread_count INT NOT NULL DEFAULT 0,
    last_message_preview VARCHAR(1024) NULL,
    last_message_time DATETIME NULL,
    last_read_time DATETIME NULL,
    status TINYINT NOT NULL DEFAULT 0,
    creator VARCHAR(64) NULL DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) NULL DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT(1) NOT NULL DEFAULT b'0',
    tenant_id BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fb_message_conversation (tenant_id, account_id, conversation_key, deleted),
    KEY idx_fb_message_conversation_last (tenant_id, last_message_time)
) COMMENT='Facebook消息会话';

CREATE TABLE IF NOT EXISTS facebook_message (
    id BIGINT NOT NULL AUTO_INCREMENT,
    conversation_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    external_message_id VARCHAR(255) NULL,
    direction VARCHAR(16) NOT NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'messenger',
    sender_user_id VARCHAR(128) NULL,
    sender_name VARCHAR(255) NULL,
    original_text TEXT NOT NULL,
    detected_language VARCHAR(64) NULL,
    translated_text TEXT NULL,
    target_language VARCHAR(64) NULL,
    translation_status TINYINT NOT NULL DEFAULT 0,
    is_read BIT(1) NOT NULL DEFAULT b'0',
    send_status TINYINT NOT NULL DEFAULT 0,
    send_task_id BIGINT NULL,
    send_detail_id BIGINT NULL,
    source_post_id VARCHAR(255) NULL,
    source_post_url VARCHAR(1024) NULL,
    source_comment_id VARCHAR(255) NULL,
    message_time DATETIME NULL,
    send_time DATETIME NULL,
    error_message VARCHAR(1024) NULL,
    creator VARCHAR(64) NULL DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) NULL DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT(1) NOT NULL DEFAULT b'0',
    tenant_id BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fb_message_external (tenant_id, account_id, source_type, external_message_id, deleted),
    KEY idx_fb_message_conversation (tenant_id, conversation_id, create_time),
    KEY idx_fb_message_unread (tenant_id, is_read, direction)
    ,KEY idx_fb_message_send_detail (tenant_id, send_detail_id)
) COMMENT='Facebook消息';
