export interface FacebookLanguageOption {
  code: string
  nativeName: string
  englishName: string
}

// 从 Facebook 语言设置弹框提取的固定清单。Facebook 的动态 class/id 不写入这里。
export const facebookLanguages: FacebookLanguageOption[] = [
  ['en_US', 'English (US)', 'English (US)'], ['zh_CN', '中文(简体)', 'Simplified Chinese (China)'],
  ['es_ES', 'Español', 'Spanish'], ['pt_BR', 'Português (Brasil)', 'Portuguese (Brazil)'],
  ['so_SO', 'Af-Soomaali', 'Somali'], ['af_ZA', 'Afrikaans', 'Afrikaans'],
  ['az_AZ', 'Azərbaycan dili', 'Azerbaijani'], ['id_ID', 'Bahasa Indonesia', 'Indonesian'],
  ['ms_MY', 'Bahasa Melayu', 'Malay'], ['jv_ID', 'Basa Jawa', 'Javanese'],
  ['ceb_PH', 'Bisaya', 'Cebuano'], ['bs_BA', 'Bosanski', 'Bosnian'],
  ['br_FR', 'Brezhoneg', 'Breton'], ['ca_ES', 'Català', 'Catalan'],
  ['cs_CZ', 'Čeština', 'Czech'], ['co_FR', 'Corsu', 'Corsican'],
  ['cy_GB', 'Cymraeg', 'Welsh'], ['da_DK', 'Dansk', 'Danish'],
  ['de_DE', 'Deutsch', 'German'], ['et_EE', 'Eesti', 'Estonian'],
  ['en_GB', 'English (UK)', 'English (UK)'], ['es_ES', 'Español', 'Spanish'],
  ['es_LA', 'Español (España)', 'Spanish (Spain)'], ['eo_EO', 'Esperanto', 'Esperanto'],
  ['eu_ES', 'Euskara', 'Basque'], ['tl_PH', 'Filipino', 'Filipino'],
  ['fo_FO', 'Føroyskt', 'Faroese'], ['fr_CA', 'Français (Canada)', 'French (Canada)'],
  ['fr_FR', 'Français (France)', 'French (France)'], ['fy_NL', 'Frysk', 'Frisian'],
  ['ff_NG', 'Fula', 'Fula'], ['fur_IT', 'Furlan', 'Friulian'],
  ['ga_IE', 'Gaeilge', 'Irish'], ['gl_ES', 'Galego', 'Galician'],
  ['gn_PY', 'Guarani', 'Guarani'], ['ha_NG', 'Hausa', 'Hausa'],
  ['hr_HR', 'Hrvatski', 'Croatian'], ['rw_RW', 'Ikinyarwanda', 'Kinyarwanda'],
  ['iu_CA', 'Inuktitut', 'Inuktitut'], ['ik_US', 'Iñupiatun', 'Inupiaq'],
  ['is_IS', 'Íslenska', 'Icelandic'], ['it_IT', 'Italiano', 'Italian'],
  ['sw_KE', 'Kiswahili', 'Swahili'], ['ht_HT', 'Kreyòl Ayisyen', 'Haitian Creole'],
  ['ku_TR', 'Kurdî (Kurmancî)', 'Northern Kurdish (Kurmanji)'], ['lv_LV', 'Latviešu', 'Latvian'],
  ['lt_LT', 'Lietuvių', 'Lithuanian'], ['hu_HU', 'Magyar', 'Hungarian'],
  ['mg_MG', 'Malagasy', 'Malagasy'], ['mt_MT', 'Malti', 'Maltese'],
  ['nl_NL', 'Nederlands', 'Dutch'], ['nb_NO', 'Norsk (bokmål)', 'Norwegian (bokmal)'],
  ['nn_NO', 'Norsk (nynorsk)', 'Norwegian (nynorsk)'], ['uz_UZ', "O'zbek", 'Uzbek'],
  ['pl_PL', 'Polski', 'Polish'], ['pt_BR', 'Português (Brasil)', 'Portuguese (Brazil)'],
  ['pt_PT', 'Português (Portugal)', 'Portuguese (Portugal)'], ['ro_RO', 'Română', 'Romanian'],
  ['sc_IT', 'Sardu', 'Sardinian'], ['sn_ZW', 'Shona', 'Shona'],
  ['sq_AL', 'Shqip', 'Albanian'], ['szl_PL', 'ślōnskŏ gŏdka', 'Silesian'],
  ['sk_SK', 'Slovenčina', 'Slovak'], ['sl_SI', 'Slovenščina', 'Slovenian'],
  ['fi_FI', 'Suomi', 'Finnish'], ['sv_SE', 'Svenska', 'Swedish'],
  ['vi_VN', 'Tiếng Việt', 'Vietnamese'], ['tr_TR', 'Türkçe', 'Turkish'],
  ['vls_BE', 'Vlaams', 'Flemish'], ['zza_TR', 'Zaza', 'Zaza'],
  ['el_GR', 'Ελληνικά', 'Greek'], ['be_BY', 'Беларуская', 'Belarusian'],
  ['bg_BG', 'Български', 'Bulgarian'], ['ky_KG', 'кыргызча', 'Kyrgyz'],
  ['kk_KZ', 'Қазақша', 'Kazakh'], ['mk_MK', 'Македонски', 'Macedonian'],
  ['mn_MN', 'Монгол', 'Mongolian'], ['ru_RU', 'Русский', 'Russian'],
  ['sr_RS', 'Српски', 'Serbian'], ['tt_RU', 'Татарча', 'Tatar'],
  ['tg_TJ', 'Тоҷикӣ', 'Tajik'], ['uk_UA', 'Українська', 'Ukrainian'],
  ['ka_GE', 'ქართული', 'Georgian'], ['hy_AM', 'Հայերեն', 'Armenian'],
  ['he_IL', 'עברית', 'Hebrew'], ['ur_PK', 'اردو', 'Urdu'],
  ['ar_AR', 'العربية', 'Arabic'], ['ps_AF', 'پښتو', 'Pashto'],
  ['fa_IR', 'فارسی', 'Persian'], ['ckb_IQ', 'کوردیی ناوەندی', 'Central Kurdish (Sorani)'],
  ['sy_SY', 'ܣܘܪܝܝܐ', 'Syriac'], ['tz_MA', 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'Tamazight'],
  ['am_ET', 'አማርኛ', 'Amharic'], ['ne_NP', 'नेपाली', 'Nepali'],
  ['mr_IN', 'मराठी', 'Marathi'], ['hi_IN', 'हिन्दी', 'Hindi'],
  ['as_IN', 'অসমীয়া', 'Assamese'], ['bn_IN', 'বাংলা', 'Bengali'],
  ['pa_IN', 'ਪੰਜਾਬੀ', 'Punjabi'], ['gu_IN', 'ગુજરાતી', 'Gujarati'],
  ['or_IN', 'ଓଡ଼ିଆ', 'Oriya'], ['ta_IN', 'தமிழ்', 'Tamil'],
  ['te_IN', 'తెలుగు', 'Telugu'], ['kn_IN', 'ಕನ್ನಡ', 'Kannada'],
  ['ml_IN', 'മലയാളം', 'Malayalam'], ['si_LK', 'සිංහල', 'Sinhala'],
  ['th_TH', 'ภาษาไทย', 'Thai'], ['lo_LA', 'ພາສາລາວ', 'Lao'],
  ['my_MM', 'မြန်မာဘာသာ', 'Burmese'], ['km_KH', 'ភាសាខ្មែរ', 'Khmer'],
  ['ko_KR', '한국어', 'Korean'], ['zh_TW', '中文(台灣)', 'Traditional Chinese (Taiwan)'],
  ['zh_CN', '中文(简体)', 'Simplified Chinese (China)'], ['zh_HK', '中文(香港)', 'Traditional Chinese (Hong Kong)'],
  ['ja_JP', '日本語', 'Japanese'], ['ja_KS', '日本語(関西)', 'Japanese (Kansai)']
].map(([code, nativeName, englishName]) => ({ code, nativeName, englishName }))
