#pragma checksum "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3A5AB8954AB23998349F2061F5FEA88B07D16622"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace SocialMatrix.WpfHost.Windows {
    
    
    /// <summary>
    /// MessageManagerWindow
    /// </summary>
    public partial class MessageManagerWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 28 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AccountSearchBox;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SelectedCountText;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox RealtimeAccountList;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox ScheduledAccountList;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid BrowserHost;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BrowserEmptyText;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border SelectionTranslationPopup;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SelectionTranslationText;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ScriptSearchButton;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ScriptSearchBox;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox ScriptList;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ScriptNextButton;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ScriptPreviousButton;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ScriptPageText;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ReplyChineseBox;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox TargetLanguageBox;
        
        #line default
        #line hidden
        
        
        #line 110 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox AutoTranslateCheckBox;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ReplyTranslatedBox;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SendButton;
        
        #line default
        #line hidden
        
        
        #line 116 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TranslateButton;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar TranslationProgress;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/SocialMatrix.WpfHost;component/windows/messagemanagerwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 24 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ManagePool_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 25 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BringOnline_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 26 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SetScheduled_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.AccountSearchBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 28 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            this.AccountSearchBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.AccountSearchBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.SelectedCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.RealtimeAccountList = ((System.Windows.Controls.ListBox)(target));
            
            #line 34 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            this.RealtimeAccountList.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.AccountList_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.ScheduledAccountList = ((System.Windows.Controls.ListBox)(target));
            
            #line 36 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            this.ScheduledAccountList.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.AccountList_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.BrowserHost = ((System.Windows.Controls.Grid)(target));
            return;
            case 9:
            this.BrowserEmptyText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.SelectionTranslationPopup = ((System.Windows.Controls.Border)(target));
            return;
            case 11:
            this.SelectionTranslationText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.ScriptSearchButton = ((System.Windows.Controls.Button)(target));
            
            #line 77 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            this.ScriptSearchButton.Click += new System.Windows.RoutedEventHandler(this.ScriptSearchButton_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.ScriptSearchBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.ScriptList = ((System.Windows.Controls.ListBox)(target));
            
            #line 80 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            this.ScriptList.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ScriptList_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 15:
            this.ScriptNextButton = ((System.Windows.Controls.Button)(target));
            
            #line 82 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            this.ScriptNextButton.Click += new System.Windows.RoutedEventHandler(this.ScriptNextButton_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.ScriptPreviousButton = ((System.Windows.Controls.Button)(target));
            
            #line 83 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            this.ScriptPreviousButton.Click += new System.Windows.RoutedEventHandler(this.ScriptPreviousButton_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.ScriptPageText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.ReplyChineseBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 90 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            this.ReplyChineseBox.LostFocus += new System.Windows.RoutedEventHandler(this.ReplyChineseBox_LostFocus);
            
            #line default
            #line hidden
            return;
            case 19:
            this.TargetLanguageBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 93 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            this.TargetLanguageBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.TargetLanguageBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 20:
            this.AutoTranslateCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 21:
            this.ReplyTranslatedBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.SendButton = ((System.Windows.Controls.Button)(target));
            
            #line 115 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            this.SendButton.Click += new System.Windows.RoutedEventHandler(this.SendButton_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.TranslateButton = ((System.Windows.Controls.Button)(target));
            
            #line 116 "..\..\SocialMatrix.WpfHost\Windows\MessageManagerWindow.xaml"
            this.TranslateButton.Click += new System.Windows.RoutedEventHandler(this.TranslateButton_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.TranslationProgress = ((System.Windows.Controls.ProgressBar)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

