<template>
  <ContentWrap>
    <div class="toolbar"><el-select v-model="status" clearable placeholder="全部状态" @change="load"><el-option v-for="item in statuses" :key="item" :label="item" :value="item" /></el-select><el-button type="primary" @click="open">新增渠道</el-button><el-button @click="importVisible=true">批量导入</el-button></div>
    <el-table v-loading="loading" :data="rows"><el-table-column prop="name" label="渠道" min-width="200"/><el-table-column prop="domain" label="域名" min-width="220"/><el-table-column prop="sourceType" label="类型" width="150"/><el-table-column prop="sourceRole" label="用途" width="180"/><el-table-column prop="priority" label="优先级" width="90"/><el-table-column prop="yieldScore" label="收益" width="90"/><el-table-column prop="status" label="状态" width="120"/><el-table-column label="操作" width="180"><template #default="{row}"><el-button link type="primary" @click="toggle(row)">{{ row.status === 'ACTIVE' ? '暂停' : '启用' }}</el-button></template></el-table-column></el-table>
    <el-dialog v-model="visible" title="新增搜索渠道" width="520px"><el-form :model="form" label-width="90px"><el-form-item label="名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="域名"><el-input v-model="form.domain" placeholder="例如 europages.com"/></el-form-item><el-form-item label="渠道类型"><el-input v-model="form.sourceType" placeholder="B2B_DIRECTORY"/></el-form-item><el-form-item label="渠道用途"><el-input v-model="form.sourceRole" placeholder="COMPANY_DISCOVERY"/></el-form-item><el-form-item label="优先级"><el-input-number v-model="form.priority" :min="0"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
    <el-dialog v-model="importVisible" title="批量导入搜索渠道" width="620px"><p class="tip">支持 JSON 数组、每行一个 JSON 对象，或每行一个域名；域名导入后默认为企业发现渠道。</p><el-input v-model="importText" type="textarea" :rows="10" placeholder='europages.com&#10;kompass.com&#10;[{"name":"Europages","domain":"europages.com"}]'/><template #footer><el-button @click="importVisible=false">取消</el-button><el-button type="primary" @click="importBatch">导入</el-button></template></el-dialog>
  </ContentWrap>
</template>
<script setup lang="ts">
import { AiSearchSourceApi, type AiSearchSourceVO } from '@/api/facebook/aiSearchSource'
const message = useMessage(); const loading = ref(false); const rows = ref<AiSearchSourceVO[]>([]); const status = ref(''); const visible = ref(false); const importVisible = ref(false); const importText = ref(''); const statuses = ['ACTIVE','CANDIDATE','LOW_YIELD','PAUSED','RETIRED']; const form = ref<AiSearchSourceVO>({ name: '', priority: 0, status: 'CANDIDATE' })
const load = async () => { loading.value = true; try { rows.value = await AiSearchSourceApi.list(status.value) } finally { loading.value = false } }
const open = () => { form.value = { name: '', priority: 0, status: 'CANDIDATE' }; visible.value = true }
const save = async () => { if (!form.value.name.trim()) return message.warning('请输入渠道名称'); await AiSearchSourceApi.create(form.value); visible.value = false; await load() }
const importBatch = async () => { try { const raw = importText.value.trim(); if (!raw) throw new Error(); let data: AiSearchSourceVO[]; try { const parsed = JSON.parse(raw); data = Array.isArray(parsed) ? parsed : [parsed] } catch { data = raw.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).map((line) => { try { return JSON.parse(line) } catch { const domain = line.replace(/^https?:\/\//, '').split('/')[0].trim().toLowerCase(); return { name: domain, domain, sourceType: 'OTHER', sourceRole: 'COMPANY_DISCOVERY', priority: 0 } } }) } if (!data.length) throw new Error(); await AiSearchSourceApi.createBatch(data); importVisible.value = false; importText.value = ''; message.success(`已提交 ${data.length} 条渠道`); await load() } catch { message.error('请输入 JSON 数组、JSONL 或域名列表') } }
const toggle = async (row: AiSearchSourceVO) => { await AiSearchSourceApi.updateStatus(row.id!, row.status === 'ACTIVE' ? 'PAUSED' : 'ACTIVE'); await load() }
onMounted(load)
</script>
<style scoped>.toolbar{display:flex;gap:12px;margin-bottom:16px}.tip{color:var(--el-text-color-secondary);font-size:13px}</style>
