CREATE TABLE IF NOT EXISTS `ai_api_key` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `name` VARCHAR(100) NOT NULL COMMENT '名称',
    `api_key` VARCHAR(255) NOT NULL COMMENT '密钥',
    `platform` VARCHAR(50) NOT NULL COMMENT '平台',
    `url` VARCHAR(500) COMMENT 'API 地址',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_platform` (`platform`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI API 秘钥表';

CREATE TABLE IF NOT EXISTS `ai_model` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `key_id` BIGINT COMMENT 'API 秘钥编号',
    `name` VARCHAR(100) NOT NULL COMMENT '模型名称',
    `model` VARCHAR(100) NOT NULL COMMENT '模型标志',
    `platform` VARCHAR(50) NOT NULL COMMENT '平台',
    `type` TINYINT NOT NULL COMMENT '类型',
    `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    `temperature` DECIMAL(5,2) COMMENT '温度参数',
    `max_tokens` INT COMMENT '单条回复的最大 Token 数量',
    `max_contexts` INT COMMENT '上下文的最大 Message 数量',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_key_id` (`key_id`),
    INDEX `idx_platform` (`platform`),
    INDEX `idx_type` (`type`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 模型表';

CREATE TABLE IF NOT EXISTS `ai_tool` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '工具编号',
    `name` VARCHAR(100) NOT NULL COMMENT '工具名称',
    `description` VARCHAR(500) COMMENT '工具描述',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_name` (`name`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 工具表';

CREATE TABLE IF NOT EXISTS `ai_chat_role` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `name` VARCHAR(100) NOT NULL COMMENT '角色名称',
    `avatar` VARCHAR(500) COMMENT '角色头像',
    `category` VARCHAR(50) COMMENT '角色分类',
    `description` VARCHAR(500) COMMENT '角色描述',
    `system_message` TEXT COMMENT '角色设定',
    `user_id` BIGINT COMMENT '用户编号',
    `model_id` BIGINT COMMENT '模型编号',
    `knowledge_ids` TEXT COMMENT '引用的知识库编号列表',
    `tool_ids` TEXT COMMENT '引用的工具编号列表',
    `mcp_client_names` TEXT COMMENT '引用的 MCP Client 名字列表',
    `public_status` TINYINT NOT NULL DEFAULT 0 COMMENT '是否公开',
    `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_model_id` (`model_id`),
    INDEX `idx_public_status` (`public_status`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 聊天角色表';

CREATE TABLE IF NOT EXISTS `ai_chat_conversation` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID 编号',
    `user_id` BIGINT NOT NULL COMMENT '用户编号',
    `title` VARCHAR(200) NOT NULL DEFAULT '新对话' COMMENT '对话标题',
    `pinned` TINYINT NOT NULL DEFAULT 0 COMMENT '是否置顶',
    `pinned_time` DATETIME COMMENT '置顶时间',
    `role_id` BIGINT COMMENT '角色编号',
    `model_id` BIGINT COMMENT '模型编号',
    `model` VARCHAR(100) COMMENT '模型标志',
    `system_message` TEXT COMMENT '角色设定',
    `temperature` DECIMAL(5,2) COMMENT '温度参数',
    `max_tokens` INT COMMENT '单条回复的最大 Token 数量',
    `max_contexts` INT COMMENT '上下文的最大 Message 数量',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_role_id` (`role_id`),
    INDEX `idx_model_id` (`model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI Chat 对话表';

CREATE TABLE IF NOT EXISTS `ai_chat_message` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `conversation_id` BIGINT NOT NULL COMMENT '对话编号',
    `reply_id` BIGINT COMMENT '回复消息编号',
    `type` VARCHAR(50) NOT NULL COMMENT '消息类型',
    `user_id` BIGINT NOT NULL COMMENT '用户编号',
    `role_id` BIGINT COMMENT '角色编号',
    `model` VARCHAR(100) COMMENT '模型标志',
    `model_id` BIGINT COMMENT '模型编号',
    `content` LONGTEXT COMMENT '聊天内容',
    `reasoning_content` LONGTEXT COMMENT '推理内容',
    `use_context` TINYINT NOT NULL DEFAULT 1 COMMENT '是否携带上下文',
    `segment_ids` TEXT COMMENT '知识库段落编号数组',
    `web_search_pages` LONGTEXT COMMENT '联网搜索的网页内容数组',
    `attachment_urls` TEXT COMMENT '附件 URL 数组',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_conversation_id` (`conversation_id`),
    INDEX `idx_reply_id` (`reply_id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_role_id` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI Chat 消息表';

CREATE TABLE IF NOT EXISTS `ai_knowledge` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `name` VARCHAR(100) NOT NULL COMMENT '知识库名称',
    `description` VARCHAR(500) COMMENT '知识库描述',
    `embedding_model_id` BIGINT COMMENT '向量模型编号',
    `embedding_model` VARCHAR(100) COMMENT '模型标识',
    `top_k` INT NOT NULL DEFAULT 5 COMMENT 'topK',
    `similarity_threshold` DECIMAL(5,4) COMMENT '相似度阈值',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_embedding_model_id` (`embedding_model_id`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 知识库表';

CREATE TABLE IF NOT EXISTS `ai_knowledge_document` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `knowledge_id` BIGINT NOT NULL COMMENT '知识库编号',
    `name` VARCHAR(200) NOT NULL COMMENT '文档名称',
    `url` VARCHAR(500) COMMENT '文件 URL',
    `content` LONGTEXT COMMENT '内容',
    `content_length` INT COMMENT '文档长度',
    `tokens` INT COMMENT '文档 token 数量',
    `segment_max_tokens` INT COMMENT '分片最大 Token 数',
    `retrieval_count` INT NOT NULL DEFAULT 0 COMMENT '召回次数',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_knowledge_id` (`knowledge_id`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 知识库-文档表';

CREATE TABLE IF NOT EXISTS `ai_knowledge_segment` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `knowledge_id` BIGINT NOT NULL COMMENT '知识库编号',
    `document_id` BIGINT COMMENT '文档编号',
    `content` LONGTEXT COMMENT '切片内容',
    `content_length` INT COMMENT '切片内容长度',
    `vector_id` VARCHAR(255) COMMENT '向量库的编号',
    `tokens` INT COMMENT 'token 数量',
    `retrieval_count` INT NOT NULL DEFAULT 0 COMMENT '召回次数',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_knowledge_id` (`knowledge_id`),
    INDEX `idx_document_id` (`document_id`),
    INDEX `idx_vector_id` (`vector_id`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 知识库-文档分段表';

CREATE TABLE IF NOT EXISTS `ai_image` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `user_id` BIGINT NOT NULL COMMENT '用户编号',
    `prompt` TEXT NOT NULL COMMENT '提示词',
    `platform` VARCHAR(50) NOT NULL COMMENT '平台',
    `model_id` BIGINT COMMENT '模型编号',
    `model` VARCHAR(100) COMMENT '模型标识',
    `width` INT COMMENT '图片宽度',
    `height` INT COMMENT '图片高度',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '生成状态',
    `finish_time` DATETIME COMMENT '完成时间',
    `error_message` VARCHAR(1000) COMMENT '绘画错误信息',
    `pic_url` VARCHAR(500) COMMENT '图片地址',
    `public_status` TINYINT NOT NULL DEFAULT 0 COMMENT '是否公开',
    `options` LONGTEXT COMMENT '绘制参数',
    `buttons` LONGTEXT COMMENT 'mj buttons 按钮',
    `task_id` VARCHAR(100) COMMENT '任务编号',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_platform` (`platform`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 绘画表';

CREATE TABLE IF NOT EXISTS `ai_mind_map` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `user_id` BIGINT NOT NULL COMMENT '用户编号',
    `platform` VARCHAR(50) NOT NULL COMMENT '平台',
    `model_id` BIGINT COMMENT '模型编号',
    `model` VARCHAR(100) COMMENT '模型',
    `prompt` TEXT COMMENT '生成内容提示',
    `generated_content` LONGTEXT COMMENT '生成的内容',
    `error_message` VARCHAR(1000) COMMENT '错误信息',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_platform` (`platform`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 思维导图表';

CREATE TABLE IF NOT EXISTS `ai_music` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `user_id` BIGINT NOT NULL COMMENT '用户编号',
    `title` VARCHAR(200) COMMENT '音乐名称',
    `lyric` TEXT COMMENT '歌词',
    `image_url` VARCHAR(500) COMMENT '图片地址',
    `audio_url` VARCHAR(500) COMMENT '音频地址',
    `video_url` VARCHAR(500) COMMENT '视频地址',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '音乐状态',
    `generate_mode` TINYINT COMMENT '生成模式',
    `description` VARCHAR(500) COMMENT '描述词',
    `platform` VARCHAR(50) COMMENT '平台',
    `model` VARCHAR(100) COMMENT '模型',
    `tags` TEXT COMMENT '音乐风格标签',
    `duration` DECIMAL(10,2) COMMENT '音乐时长',
    `public_status` TINYINT NOT NULL DEFAULT 0 COMMENT '是否公开',
    `task_id` VARCHAR(100) COMMENT '任务编号',
    `error_message` VARCHAR(1000) COMMENT '错误信息',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_platform` (`platform`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 音乐表';

CREATE TABLE IF NOT EXISTS `ai_write` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `user_id` BIGINT NOT NULL COMMENT '用户编号',
    `type` TINYINT NOT NULL COMMENT '写作类型',
    `platform` VARCHAR(50) NOT NULL COMMENT '平台',
    `model_id` BIGINT COMMENT '模型编号',
    `model` VARCHAR(100) COMMENT '模型',
    `prompt` TEXT COMMENT '生成内容提示',
    `generated_content` LONGTEXT COMMENT '生成的内容',
    `original_content` LONGTEXT COMMENT '原文',
    `length` TINYINT COMMENT '长度提示词',
    `format` TINYINT COMMENT '格式提示词',
    `tone` TINYINT COMMENT '语气提示词',
    `language` TINYINT COMMENT '语言提示词',
    `error_message` VARCHAR(1000) COMMENT '错误信息',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_platform` (`platform`),
    INDEX `idx_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 写作表';

CREATE TABLE IF NOT EXISTS `ai_workflow` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `name` VARCHAR(100) NOT NULL COMMENT '工作流名称',
    `code` VARCHAR(100) NOT NULL COMMENT '工作流标识',
    `graph` LONGTEXT COMMENT '工作流模型 JSON 数据',
    `remark` VARCHAR(500) COMMENT '备注',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT COMMENT '创建者',
    `update_by` BIGINT COMMENT '更新者',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_code_deleted` (`tenant_id`, `code`, `deleted`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 工作流表';
